# Generated by Django 2.2.3 on 2019-12-04 12:55

from django.db import migrations

def strip_zeros_from_societies(apps, schema_editor):
    Writer = apps.get_model('music_publisher', 'Writer')
    for writer in Writer.objects.filter(pr_society__isnull=False):
        writer.pr_society = writer.pr_society.lstrip('0')
        writer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(strip_zeros_from_societies, migrations.RunPython.noop),
    ]
