# Generated by Django 3.2.6 on 2021-08-16 15:15

from django.db import migrations, models
from datetime import datetime


def set_created_on(apps, schema_editor):
    CWRExport = apps.get_model('music_publisher', 'CWRExport')
    qs = CWRExport.objects.filter(created_on__isnull=True)
    for obj in qs:
        if obj.version in ['21', '22']:
            s = obj.cwr[64:78]
        else:
            s = obj.cwr[65:79]
        obj.created_on = datetime.strptime(s, '%Y%m%d%H%M%S')
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0002_mayday'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwrexport',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RunPython(
            code=set_created_on,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
