# Generated by Django 3.2.7 on 2021-09-08 06:51

from django.db import migrations, models
import django.db.models.deletion
import music_publisher.base


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0003_cwrexport_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music_publisher.release',),
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to),
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='label',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to),
        ),
        migrations.AddField(
            model_name='release',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to, verbose_name='Cover Art'),
        ),
        migrations.AddField(
            model_name='writer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to),
        ),
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_publisher.release'),
        ),
    ]
