# Generated by Django 3.2.7 on 2021-09-01 09:27

from django.db import migrations, models
import music_publisher.base


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0003_cwrexport_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to),
        ),
        migrations.AddField(
            model_name='label',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to),
        ),
        migrations.AddField(
            model_name='writer',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to=music_publisher.base.upload_to),
        ),
    ]
