# Generated by Django 3.2.7 on 2021-09-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0004_auto_20210901_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music_publisher.release',),
        ),
    ]
