# Generated by Django 2.1.7 on 2019-07-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0004_auto_20190712_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternatetitle',
            options={'ordering': ('-suffix', 'title')},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('last_name', 'first_name', '-id'), 'verbose_name': 'Performing Artist', 'verbose_name_plural': ' Performing Artists'},
        ),
        migrations.AlterModelOptions(
            name='artistinwork',
            options={'ordering': ('artist__last_name', 'artist__first_name'), 'verbose_name': 'Performing artist', 'verbose_name_plural': 'Performing artists (not mentioned in recordings section)'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('name',), 'verbose_name_plural': 'Music Labels'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ('name',), 'verbose_name_plural': 'Music Libraries'},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ('-id',), 'verbose_name_plural': '  Recordings'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('release', 'cut_number')},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-id',), 'verbose_name_plural': '   Works'},
        ),
        migrations.AddField(
            model_name='recording',
            name='releases',
            field=models.ManyToManyField(related_name='releases', through='music_publisher.Track', to='music_publisher.Release'),
        ),
        migrations.AddField(
            model_name='release',
            name='recordings',
            field=models.ManyToManyField(related_name='recordings', through='music_publisher.Track', to='music_publisher.Recording'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_publisher.Work'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('recording', 'release'), ('release', 'cut_number')},
        ),
    ]
