# Generated by Django 3.2.6 on 2021-09-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0005_auto_20210908_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistinwork',
            options={'ordering': ('artist__last_name', 'artist__first_name'), 'verbose_name': 'Artist performing', 'verbose_name_plural': 'Artists performing (not mentioned in recordings section)'},
        ),
    ]
