# Generated by Django 3.0.6 on 2020-06-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0005_work__work_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_file', models.FileField(upload_to='')),
                ('out_file', models.FileField(upload_to='')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
