# Generated by Django 2.2.3 on 2019-07-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0005_auto_20190715_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ackimport',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'CWR ACK Import'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('last_name', 'first_name', '-id'), 'verbose_name': 'Performing Artist', 'verbose_name_plural': '  Performing Artists'},
        ),
        migrations.AlterModelOptions(
            name='commercialrelease',
            options={'verbose_name_plural': ' Commercial Releases'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('name',), 'verbose_name_plural': ' Music Labels'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ('name',), 'verbose_name_plural': ' Music Libraries'},
        ),
        migrations.AlterModelOptions(
            name='libraryrelease',
            options={'verbose_name_plural': ' Library Releases'},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ('-id',), 'verbose_name_plural': '   Recordings'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-id',), 'verbose_name_plural': '    Works'},
        ),
        migrations.AlterModelOptions(
            name='workacknowledgement',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'Registration Acknowledgement'},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ('last_name', 'first_name', 'ipi_name', '-id'), 'verbose_name_plural': '  Writers'},
        ),
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='releases',
            field=models.ManyToManyField(through='music_publisher.Track', to='music_publisher.Release'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='music_publisher.Work'),
        ),
        migrations.AlterField(
            model_name='release',
            name='recordings',
            field=models.ManyToManyField(through='music_publisher.Track', to='music_publisher.Recording'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music_publisher.Recording'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music_publisher.Release'),
        ),
    ]
