# Generated by Django 3.2.6 on 2021-09-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0006_auto_20210903_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
