# Generated by Django 2.2.3 on 2019-07-17 15:17

from django.db import migrations

def remove_leading_zeros(apps, schema_edito):
    """Create Label objects and link to """
    Writer = apps.get_model('music_publisher', 'Writer')
    for writer in Writer.objects.all():
        if not self.pr_society:
            continue
        writer.pr_society = writer.pr_society.lstrip('0')
        writer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0006_auto_20190717_1428'),
    ]

    operations = [
        migrations.RunPython(
            code=remove_leading_zeros,
        ),
    ]
