# Generated by Django 2.2.3 on 2019-07-29 10:40

from django.db import migrations, models
import music_publisher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0008_auto_20190723_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialrelease',
            options={'verbose_name_plural': '  Commercial Releases'},
        ),
        migrations.AlterModelOptions(
            name='cwrexport',
            options={'ordering': ('-id',), 'verbose_name': 'CWR Export', 'verbose_name_plural': ' CWR Exports'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('name',), 'verbose_name_plural': '  Music Labels'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ('name',), 'verbose_name_plural': '  Music Libraries'},
        ),
        migrations.AlterModelOptions(
            name='libraryrelease',
            options={'verbose_name_plural': '  Library Releases'},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ('-id',), 'verbose_name_plural': '  Recordings'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-id',), 'verbose_name': '    Musical Work'},
        ),
        migrations.AlterField(
            model_name='cwrexport',
            name='nwr_rev',
            field=models.CharField(choices=[('NWR', 'CWR 2.1: New work registrations'), ('REV', 'CWR 2.1: Revisions of registered works'), ('WRK', 'CWR 3.0: Work registration (experimental)')], db_index=True, default='NWR', max_length=3, verbose_name='CWR version/type'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='pr_society',
            field=models.CharField(blank=True, choices=[('55', 'SABAM, Belgium'), ('101', 'SOCAN, Canada'), ('88', 'CMRRA, Canada'), ('40', 'KODA, Denmark'), ('89', 'TEOSTO, Finland'), ('58', 'SACEM, France'), ('35', 'GEMA, Germany'), ('74', 'SIAE, Italy'), ('23', 'BUMA, Netherlands'), ('78', 'STEMRA, Netherlands'), ('90', 'TONO, Norway'), ('79', 'STIM, Sweden'), ('52', 'PRS, United Kingdom'), ('44', 'MCPS, United Kingdom'), ('10', 'ASCAP, United States'), ('21', 'BMI, United States'), ('71', 'SESAC Inc., United States'), ('34', 'HFA, United States'), ('319', 'ICE Services, Administrative Agency'), ('707', 'Musicmark, Administrative Agency')], max_length=3, null=True, validators=[music_publisher.validators.CWRFieldValidator('writer_pr_society')], verbose_name='Performance rights society'),
        ),
    ]
