# Generated by Django 4.2.13 on 2024-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_publisher", "0010_alter_alternatetitle_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternatetitle",
            name="title_type",
            field=models.CharField(
                choices=[
                    ("AT", "Alternative Title"),
                    ("TE", "First Line of Text"),
                    ("FT", "Formal Title"),
                    ("IT", "Incorrect Title"),
                    ("ET", "Extra Search Title"),
                ],
                default="AT",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title_type",
            field=models.CharField(
                choices=[
                    ("AT", "Alternative Title"),
                    ("TE", "First Line of Text"),
                    ("FT", "Formal Title"),
                    ("IT", "Incorrect Title"),
                    ("ET", "Extra Search Title"),
                ],
                default="AT",
                max_length=2,
            ),
        ),
    ]
