# Generated by Django 4.2.17 on 2024-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_publisher", "0011_alter_alternatetitle_title_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cwrexport",
            name="cwr_file_zipped",
            field=models.FileField(blank=True, editable=False, null=True, upload_to=""),
        ),
    ]
