# Generated by Django 5.2.13 on 2026-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_publisher", "0012_alter_cwrexport_nwr_rev_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cwrexport",
            name="options",
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
