# Generated by Django 5.2.13 on 2026-05-14 15:17

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_publisher", "0013_cwrexport_options"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
