# Generated by Django 5.2.13 on 2026-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_publisher", "0014_work_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwrexport",
            name="options",
            field=models.JSONField(default=dict, editable=False, null=True),
        ),
    ]
