# Generated by Django 2.1.4 on 2018-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0018_auto_20181226_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerinwork',
            name='capacity',
            field=models.CharField(blank=True, choices=[('CA', 'Composer&Lyricist'), ('C ', 'Composer'), ('A ', 'Lyricist'), ('AR', 'Arranger'), ('AD', 'Adaptor'), ('TR', 'Translator')], max_length=2),
        ),
    ]
