# Generated by Django 2.1.4 on 2019-01-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0020_auto_20190121_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwrexport',
            name='_work_count',
        ),
    ]
