# Generated by Django 2.1.5 on 2019-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_publisher', '0022_cwrexport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatetitle',
            name='suffix',
            field=models.BooleanField(default=False, help_text='Use this field if it is to be added to the title'),
        ),
        migrations.AlterField(
            model_name='cwrexport',
            name='description',
            field=models.CharField(blank=True, max_length=60, verbose_name='Internal Note'),
        ),
    ]
